
name: Entrega final - API de Compras de Livros

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Run controller tests
      run: npm run test-rest-controller

    - name: Start REST
      run: npm run start-rest &

    - name: Start GraphQL
      run: npm run start-graphql &

    - name: Wait services
      run: sleep 8

    - name: Create .env
      run: |
        echo "BASE_URL_REST=${{ secrets.BASE_URL_REST }}" >> .env
        echo "BASE_URL_GRAPHQL=${{ secrets.BASE_URL_GRAPHQL }}" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

    - name: Run REST external tests
      run: npm run test-rest-external
